#!/bin/bash
#Copyright (c) 2017 Spot Communications, Inc.
iptables -F
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
systemctl restart scfw
